title: ''
url: ''
baseurl: ''
source: 'src'

collections:
  csv_collection:
    output: true
    source: valid.csv
    id_key: pid
    layout: test
    split:
      - key: tags
        separator: ';'
  json_collection:
    output: true
    source: valid.json
    id_key: pid
    layout: test
  yaml_collection:
    output: true
    source: valid.yml
    id_key: pid
    layout: test
