AllCops:
  NewCops: enable
  TargetRubyVersion: 2.4
  SuggestExtensions: false
Style/MixinUsage:
  Enabled: false
Metrics/MethodLength:
  Max: 25
Metrics/AbcSize:
  Max: 25
Metrics/BlockLength:
  Max: 50
Layout/EmptyComment:
  Enabled: false # Temporary
Layout/LineLength:
  Max: 100
  AllowedPatterns:
    - 'raise'
    - 'puts'
    - 'expect'
