# fill in test yml
name: Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.1
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Run tests
        run: bundle exec rspec